//b2 dinh nghia action types
export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';

export const ADD_STAFF_SUCCESS = "ADD_STAFF_SUCCESS";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";

export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_LOADING = "DELETE_STAFF_LOADING";